### PR TITLE
Implement Load Balancer with Round Robin Algorithm

### PR DESCRIPTION
**Pull request by Arpit529Srivastava**
issue #2  resolved
### What does this PR do?
-This PR introduces a load balancer using the Round Robin algorithm to distribute incoming API requests evenly across multiple servers.
-It integrates APIs for Books, Student, and Movies, ensuring balanced traffic handling for each API.
-Adds server health checks to manage and remove unresponsive servers temporarily.
-Implements logging for tracking request distribution and server performance.

@ThanhCorn @chrisng0 please review this pr and add hactoberfest-accepted label to it and merge it.

Thanku for the opportunity

### CODE REVIEW

**Comment by ThanhCorn** [comment]
Can you group the APIs, only using 1 port but with multiple paths. And plz move the folder into folder algorithm then I will merge this pr later

**Comment by Arpit529Srivastava** [comment]
sure i can

**Comment by Arpit529Srivastava** [comment]
just want one clarification you want only one api port not 3 and also to move it into the algorithm folder
and shall i close the pr or just create a new one
@ThanhCorn

**Comment by ThanhCorn** [comment]
yes only 1 port, just like this
- ("/movies", GetMovies)
- ("/books", GetBooks)

keep push ur code to this pr

**Comment by Arpit529Srivastava** [comment]
@ThanhCorn check the changes
if any error are there do let me know

**Comment by Arpit529Srivastava** [comment]
@ThanhCorn review it once

**Pull request merged**
